### ISSUE TITLE
Unexpected Internal Bot Error when Executing `about` command

### ISSUE THREAD

**Issue by HTGAzureX1212** [TeamHarTex/HarTex#66]
### Bot Version

1.26.0-nightly (e2492de43 2021-12-25)

### Description

Running the `about` command is enough to cause an IBE (only visible in local terminal, however).

### Steps to Reproduce

1. Execute any bot command.
2. IBE appears in the console (after making the interaction reponse).

### Error/Stack Backtrace

```shell
2021-12-25T08:52:02.973609Z ERROR panic handler: hartex_driver: unexpected panic occurred, invoking panic handler...
2021-12-25T08:52:02.974121Z ERROR panic handler: hartex_driver: error: internal bot error: unexpected panic
2021-12-25T08:52:02.974534Z ERROR panic handler: hartex_driver: note: the bot unexpectedly panicked. this is a bug.
2021-12-25T08:52:02.9748513Z ERROR panic handler: hartex_driver: note: we would appreciate a bug report: https://github.com/HarTexTeam/HarTex-rust-discord-bot/issues/new?assignees=&labels=Bot%3A+Bug%2CBot%3A+IBE&template=internal-bot-error.yml
thread 'hartex' panicked at 'Duration too far into the future: TryFromIntError(())', C:\Users\harry\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.15.0\src\time\driver\mod.rs:132:23
stack backtrace:
   0:     0x7ff7d137d20f - std::backtrace_rs::backtrace::dbghelp::trace
                               at /rustc/c09a9529c51cde41c1101e56049d418edb07bf71\/library\std\src\..\..\backtrace\src\backtrace\dbghelp.rs:98
   1:     0x7ff7d137d20f - std::backtrace_rs::backtrace::trace_unsynchronized
                               at /rustc/c09a9529c51cde41c1101e56049d418edb07bf71\/library\std\src\..\..\backtrace\src\backtrace\mod.rs:66
   2:     0x7ff7d137d20f - std::sys_common::backtrace::_print_fmt
                               at /rustc/c09a9529c51cde41c1101e56049d418edb07bf71\/library\std\src\sys_common\backtrace.rs:67
   3:     0x7ff7d137d20f - std::sys_common::backtrace::_print::impl$0::fmt
                               at /rustc/c09a9529c51cde41c1101e56049d418edb07bf71\/library\std\src\sys_common\backtrace.rs:46
   4:     0x7ff7d139744a - core::fmt::write
                               at /rustc/c09a9529c51cde41c1101e56049d418edb07bf71\/library\core\src\fmt\mod.rs:1149
   5:     0x7ff7d1375bc8 - std::io::Write::write_fmt<std::sys::windows::stdio::Stderr>
                               at /rustc/c09a9529c51cde41c1101e56049d418edb07bf71\/library\std\src\io\mod.rs:1660
   6:     0x7ff7d137fdf6 - std::sys_common::backtrace::_print
                               at /rustc/c09a9529c51cde41c1101e56049d418edb07bf71\/library\std\src\sys_common\backtrace.rs:49
   7:     0x7ff7d137fdf6 - std::sys_common::backtrace::print
                               at /rustc/c09a9529c51cde41c1101e56049d418edb07bf71\/library\std\src\sys_common\backtrace.rs:36
   8:     0x7ff7d137fdf6 - std::panicking::default_hook::closure$1
                               at /rustc/c09a9529c51cde41c1101e56049d418edb07bf71\/library\std\src\panicking.rs:211
   9:     0x7ff7d137f8d9 - std::panicking::default_hook
                               at /rustc/c09a9529c51cde41c1101e56049d418edb07bf71\/library\std\src\panicking.rs:228
  10:     0x7ff7d0e6b582 - hartex_driver::pre_startup::pre_startup::h0d6a974b6dc492e3
  11:     0x7ff7d13804e9 - std::panicking::rust_panic_with_hook
                               at /rustc/c09a9529c51cde41c1101e56049d418edb07bf71\/library\std\src\panicking.rs:610
  12:     0x7ff7d138026b - std::panicking::begin_panic_handler::closure$0
                               at /rustc/c09a9529c51cde41c1101e56049d418edb07bf71\/library\std\src\panicking.rs:502
  13:     0x7ff7d137db37 - std::sys_common::backtrace::__rust_end_short_backtrace<std::panicking::begin_panic_handler::closure$0,never$>
                               at /rustc/c09a9529c51cde41c1101e56049d418edb07bf71\/library\std\src\sys_common\backtrace.rs:139
  14:     0x7ff7d137ff99 - std::panicking::begin_panic_handler
                               at /rustc/c09a9529c51cde41c1101e56049d418edb07bf71\/library\std\src\panicking.rs:498
  15:     0x7ff7d13b8d90 - core::panicking::panic_fmt
                               at /rustc/c09a9529c51cde41c1101e56049d418edb07bf71\/library\core\src\panicking.rs:107
  16:     0x7ff7d13b8ea3 - core::result::unwrap_failed
                               at /rustc/c09a9529c51cde41c1101e56049d418edb07bf71\/library\core\src\result.rs:1661
  17:     0x7ff7d133c3e2 - tokio::time::driver::ClockTime::instant_to_tick::hb09fc61af4f5ae7e
  18:     0x7ff7d13255f2 - tokio::time::driver::entry::TimerEntry::reset::h980cbb0a6a2b97d6
  19:     0x7ff7d13258be - tokio::time::driver::entry::TimerEntry::poll_elapsed::h1c937c14242e2710
  20:     0x7ff7d13402fa - <tokio::time::driver::sleep::Sleep as core::future::future::Future>::poll::h94dbecead22191dd
  21:     0x7ff7d1276921 - <tokio::time::timeout::Timeout<T> as core::future::future::Future>::poll::hfed0b72676b119b3
  22:     0x7ff7d127cf23 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h69c4e9f92bde682c
  23:     0x7ff7d127d704 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hf8ba951c0be352ba
  24:     0x7ff7d127c682 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h3f2a734b680a7dd6
  25:     0x7ff7d127e3ea - tokio::runtime::task::core::CoreStage<T>::poll::hfd8abba14a71190d
  26:     0x7ff7d1275b84 - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::hfab6fec72e8f0dcf
  27:     0x7ff7d127f470 - std::panicking::try::h6ce3b95beeb909de
  28:     0x7ff7d127f379 - tokio::runtime::task::harness::poll_future::h8999752409be1045
  29:     0x7ff7d127ea68 - tokio::runtime::task::harness::Harness<T,S>::poll_inner::hf7a2919a07266b0e
  30:     0x7ff7d127e882 - tokio::runtime::task::harness::Harness<T,S>::poll::h01590a56374291f3
  31:     0x7ff7d132ccf0 - std::thread::local::LocalKey<T>::with::hf145840727bd0dbb
  32:     0x7ff7d1331d53 - tokio::runtime::thread_pool::worker::Context::run::h76cf10d010c42a82
  33:     0x7ff7d13314ef - tokio::runtime::thread_pool::worker::Context::run::h76cf10d010c42a82
  34:     0x7ff7d1329a17 - tokio::macros::scoped_tls::ScopedKey<T>::set::h0a2edf51c33d187a
  35:     0x7ff7d133130f - tokio::runtime::thread_pool::worker::run::hb34f282aeff08b7b
  36:     0x7ff7d133c295 - <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll::h955239ac3604b766
  37:     0x7ff7d132da44 - tokio::runtime::task::core::CoreStage<T>::poll::h1691e27151592b8a
  38:     0x7ff7d132abd9 - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::he91893e612a75b7d
  39:     0x7ff7d132b33d - std::panicking::try::h5653e34b5c490fa3
  40:     0x7ff7d1338f22 - tokio::runtime::task::harness::poll_future::habe7f4d6be185394
  41:     0x7ff7d133815d - tokio::runtime::task::harness::Harness<T,S>::poll_inner::hf6063241bdd2fc26
  42:     0x7ff7d1337f75 - tokio::runtime::task::harness::Harness<T,S>::poll::hff4cee5968e8965a
  43:     0x7ff7d1337b37 - tokio::runtime::task::UnownedTask<S>::run::h2afaa8df098d5141
  44:     0x7ff7d133bb6e - tokio::runtime::blocking::pool::Inner::run::h372a533e83fab8f9
  45:     0x7ff7d132a46e - std::sys_common::backtrace::__rust_begin_short_backtrace::h400672831341a7ba
  46:     0x7ff7d132b7e2 - std::panicking::try::hb4dd544ea0494359
  47:     0x7ff7d132c08f - <&T as core::fmt::Debug>::fmt::hb60d762610cf095a
  48:     0x7ff7d138447c - alloc::boxed::impl$44::call_once
                               at /rustc/c09a9529c51cde41c1101e56049d418edb07bf71\library\alloc\src\boxed.rs:1811
  49:     0x7ff7d138447c - alloc::boxed::impl$44::call_once
                               at /rustc/c09a9529c51cde41c1101e56049d418edb07bf71\library\alloc\src\boxed.rs:1811
  50:     0x7ff7d138447c - std::sys::windows::thread::impl$0::new::thread_start
                               at /rustc/c09a9529c51cde41c1101e56049d418edb07bf71\/library\std\src\sys\windows\thread.rs:58
  51:     0x7ff8d3367034 - BaseThreadInitThunk
  52:     0x7ff8d5062651 - RtlUserThreadStart
```

**Comment by HTGAzureX1212** [comment]
Fixed with `twilight-http-ratelimiting 0.8.2`, but that is a temporary fix.
